version: '3'
services:
  redis-server:
    image: "redis"
    ports:
        - 17648:6379

  popup-app:
    image: leeseungryeol/popupstore:1.0
    ports:
        - "80:3000"
    environment:
            - CHOKIDAR_USEPOLLING=true